// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeXcucj0-2BnCHduUsvCn47H-YxlwaMcM',
    appId: '1:429426743300:web:171debc7a0736a429c7d51',
    messagingSenderId: '429426743300',
    projectId: 'fridge-proj',
    authDomain: 'fridge-proj.firebaseapp.com',
    storageBucket: 'fridge-proj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1nr34LRNMF5Ym46g1-oO_yBJPCMfFvSk',
    appId: '1:429426743300:android:53e379a2f400aa4b9c7d51',
    messagingSenderId: '429426743300',
    projectId: 'fridge-proj',
    storageBucket: 'fridge-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1yt6o-oGInE26JtgNOC8LqaPpRMH5px0',
    appId: '1:429426743300:ios:2f6f8c70b7275fd79c7d51',
    messagingSenderId: '429426743300',
    projectId: 'fridge-proj',
    storageBucket: 'fridge-proj.firebasestorage.app',
    iosBundleId: 'com.refrigeratorapp.refrigeratorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1yt6o-oGInE26JtgNOC8LqaPpRMH5px0',
    appId: '1:429426743300:ios:2f6f8c70b7275fd79c7d51',
    messagingSenderId: '429426743300',
    projectId: 'fridge-proj',
    storageBucket: 'fridge-proj.firebasestorage.app',
    iosBundleId: 'com.refrigeratorapp.refrigeratorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeXcucj0-2BnCHduUsvCn47H-YxlwaMcM',
    appId: '1:429426743300:web:0774aab1881430b19c7d51',
    messagingSenderId: '429426743300',
    projectId: 'fridge-proj',
    authDomain: 'fridge-proj.firebaseapp.com',
    storageBucket: 'fridge-proj.firebasestorage.app',
  );

}